[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "astroquery>=0.4.10",
    "flask>=3.1.1",
    "matplotlib>=3.10.3",
    "requests>=2.32.3",
    "sift-stack-py>=0.5.2",
]
