[project]
name = "solar-system-missions"
version = "0.1.0"
description = "Explore and visualize spacecraft trajectories using JPL Horizons data."
authors = [{ name = "SimpleCaci" }]
requires-python = ">=3.11"
dependencies = [
    "astroquery>=0.4.10",
    "flask>=3.1.1",
    "google-genai>=1.0.0",
    "matplotlib>=3.10.3",
    "requests>=2.32.3",
    "sift-stack-py>=0.5.2",
]
